name: 'Build and tests'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, reopened ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Setup Prerequisites'
        uses: ./.github/actions/setup-prerequisites

      - name: 'Setup Android SDK'
        uses: android-actions/setup-android@v3

      - name: 'Run unit tests'
        run: ./gradlew --no-daemon :secrets-gradle-plugin:validatePlugins :secrets-gradle-plugin:test :secrets-gradle-plugin-test:testDevelopmentDebugUnitTest

#      https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
      - name: 'Enable KVM group perms'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: 'Run instrumentation test'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          disable-animations: true
          script: ./gradlew --no-daemon connectedDevelopmentDebugAndroidTest